### PR TITLE
Backported the Reinforcement Modifier item from 1.12.2

### PR DESCRIPTION
**Pull request by Ethryan**
Backported the Reinforcement Modifier item from 1.12.2, so you don't have to use an Obsidian Plate Anymore.
image

image

### CODE REVIEW

**Comment by Alexdoru** [comment]
what happens to players that have obsidian plates stored in their chests ?

**Comment by Ethryan** [comment]
The plates are still there, you just use a new item to add the reinforced modifier

**Comment by Ethryan** [comment]
Still working on this, i need to fix the book too.

**Comment by Ethryan** [comment]
Ready for review.

**Comment by Dream-Master** [comment]
@Ethryan did you testing this on existing tools?

**Comment by Ethryan** [comment]
Yes, pic 1 is me testing it all the way to unbreakable

**Comment by Ethryan** [comment]
But i havn't added it to the pack, i ran it through Intellij, in dev env while testing.

**Comment by Ethryan** [comment]
Tested in main pack with a scratchbuilt tool, no problems found @Dream-Master

**Comment by Ethryan** [comment]
Anything missing here?,
Otherwise I think this is ready to merge.

**Review by OneEyeMaker — APPROVED** [review]

**Pull request merged**
