### PR TITLE
CraftingStation side chest now work with any IInventory with a configurable blacklist.

### PR DESCRIPTION
**Pull request by mitchej123**

### CODE REVIEW

**Comment by mitchej123** [comment]
Needs to blacklist GT machines, otherwise you can take the ghost circuit item, or the fluid display item :rofl:

**Comment by bombcar** [comment]
Given how many IInventories there are may it be better to *whitelist* instead the ones we think of?

well, blacklisting does allow for fun when people realize you can use it to mess with things for amusing bugs

**Comment by mitchej123** [comment]
Will switch it to a whitelist instead; just need a list of acceptable TEs

**Comment by Dream-Master** [comment]
@mitchej123 how the format of the list ? Did you make an example ?

**Comment by bombcar** [comment]
```
CraftingStationBlacklist = wanion.avaritiaddons.block.chest.infinity.TileEntityInfinityChest
```

for example. @mitchej123 is going to test using ISided to see if that cleans out most of the bad stuff and lets us use a blacklist.

**Comment by mitchej123** [comment]
It'll auto generate on first start

```
craftingstationblacklist {
    S:tileEntities <
        wanion.avaritiaddons.block.chest.infinity.TileEntityInfinityChest
     >
}
```

Hold off on merging while we update a few things here.

**Comment by slprime** [comment]
Tool Forge
image

Stencil Table
image

Type Filter (you wrote about it)
image

Quantum Tank (you wrote about it)
image

Compressed Chest (padding left is big. Mouse Wheel shouldn't work for scroll?)
image

Electronics Assembler (allows to insert an invalid item)
image
image

Me Drive (works like Electronics Assembler)
image

maybe need whitelist?

**Comment by mitchej123** [comment]
Current plan is to check for ISidedInventory and isAccessible.  If it doesn't implement that, fall back to IInventory.  

If GT machines are still accessible, I'm going to blacklist GT_Holo_Slot, etc.  Will revisit what needs blacklisting after that.

**Review by slprime — APPROVED** [review]

**Comment by meonester** [comment]
Unfortunately Shift Clicking items from recipes stopped working in TC crafting bench.

**Comment by mitchej123** [comment]
> Tool Forge (Incorrect title) 

The title is whatever is provided by the tile.  With ISidedInventory this is no longer accessible.

> 
> #### Stencil Table (Incorrect title & disappear items)

Same

> #### Type Filter (you wrote about it)
It's spiting the items out; seems fine.

> #### Quantum Tank (you wrote about it)

Fluid no longer shows up

> #### Compressed Chest (padding left is big. Mouse Wheel shouldn't work for scroll?)

Not sure what the issue is here? Looks fine to me.

Don't have the other mods on my test instance ATM, I think ISidedInventory and getAccessibleSlots should solve most of these.

**Comment by mitchej123** [comment]
Should be good for review/merge now.

**Comment by mitchej123** [comment]
hmm, definitely broke something with the NEI recipe moving....

**Comment by mitchej123** [comment]
Ok think it's all fixed now!

**Pull request merged**
