### PR TITLE
Remove restrictions to rename a tool in ToolStation

### PR DESCRIPTION
**Pull request by Worive**
Close GTNewHorizons/GT-New-Horizons-Modpack#16035

### CODE REVIEW

**Comment by wlhlm** [comment]
Please run `spotlessApply`. CI is not happy.

**Comment by Worive** [comment]
> Please run `spotlessApply`. CI is not happy.

Seems like I forgot to disable the IntelliJ IDEA "Optimize Imports", which has been performed just before commit 😅 Disabled for good now 👌

**Review by chochem — CHANGES_REQUESTED** [review]
You should change it properly and not just switch that method to true while leaving dead code around it. That is if we actually want to change this.

I have to say I dont see why we would want to change this behaviour, it seems to work as intended. But I guess I don't really care.

**Comment by chochem** [comment]
can you also say why you want to change this?
the people in the ticket simply didnt know how it works, so that would not be a good reason.

**Comment by Worive** [comment]
> can you also say why you want to change this? the people in the ticket simply didnt know how it works, so that would not be a good reason.

No reason, it was simply in "ready for development" so I checked it out. Did think it was already approved or something to have the label

**Comment by chochem** [comment]
Not all tickets are correct ;)
there is a comment in the code explaining things, so I assumed you saw that. maybe you didnt.

**Comment by Worive** [comment]
Closing PR as the change is not needed any more. Thanks @chochem, for the clarification.

**Pull request closed without merging**
