### PR TITLE
Replace some hard-coded tooltips with translatable text

### PR DESCRIPTION
**Pull request by StrangeMan1580**
About "gadgets.slime_boots.tooltip3= to stop bouncing."...
It have to be non hard-coded space after "=", because in the russian language (and possibly in some others) there should be a comma after the button name. Example: "Зажмите shift, чтобы увидеть доп. информацию"

### CODE REVIEW

**Comment by Dream-Master** [comment]
@StrangeMan1580 can you run "gradlew spotlessaply" ?

**Comment by StrangeMan1580** [comment]
I probably don't know how, because i not very good at all this Git Hub stuff...

**Comment by Dream-Master** [comment]
@StrangeMan1580 merge this <https://github.com/StrangeMan1580/TinkersConstruct/pull/1>

**Comment by StrangeMan1580** [comment]
Done

**Review by minecraft7771 — APPROVED** [review]

**Pull request merged**
