### PR TITLE
Expand tree detecting and chopping range of lumber axe

### PR DESCRIPTION
**Pull request by HoleFish**
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17457
Lumber axe can now chop down the entire tree with branches, such as large oak tree, greatwood tree and sacred oak tree. not including redwood tree

### CODE REVIEW

**Review by OneEyeMaker — APPROVED** [review]

**Comment by leumasme** [comment]
How is this supposed to work?
```java
SortedSet<ChunkPosition> visited = new TreeSet<>(Comparator.comparingInt((ChunkPosition a) -> a.chunkPosY));

// ...

if (!block.isWood(world, curX, curY, curZ)) {
    continue;
}
if (!visited.add(candidate)) {
    continue;
}
// add the current layer and above
for (int offX = 0; offX < 3; offX++) {
    for (int offY = 0; offY < 2; offY++) {
        for (int offZ = 0; offZ < 3; offZ++) {
            ChunkPosition newCandidate = new ChunkPosition(curX - 1 + offX, curY + offY, curZ - 1 + offZ);
            if (!visited.contains(newCandidate)) {
                candidates.add(newCandidate);
            }
        }
    }
}
```
The treeset comparator is the y position, so no two entries in the set can have the same y position.
Thus, adding an entry on the current layer will never work because the current layer y position already has an entry in the visited set...

Adding debug statements confirms that all the new entries that are on the same height just get skipped right away. Y=71 is the block i broke first, and immediately it tries to add Y=71 elements which get skipped.
image

**Comment by leumasme** [comment]
This also doesn't even properly solve the issue it was supposed to address, it just adds a bias to move the scanning in the +X +Z direction (instead of a bias to move straight up first).

An example tree, which would have been detected as a valid tree before, but now fails because the code travels up the leaveless branch in the +X+Z direction:

https://github.com/user-attachments/assets/f844b6fa-2e09-46f1-a115-e7d06488bd1e

If you instead rotate this tree so that the branch is in the -X -Z direction, it does get detected as a tree.

**Comment by mitchej123** [comment]
> How is this supposed to work?

The comparator is about sorting I believe, not equality... Look at your log it is definitely adding multiple values with the same Y...

image

**Comment by leumasme** [comment]
> The comparator is about sorting I believe, not equality...

I thought the same thing, but no. Sorry my log messages were confusing, the logging was about adding to the stack because it wasn't in the set yet, not about adding to the visited set. Adding to the visited set only happens later when iterating over the stack.

**Pull request merged**
