### PR TITLE
Totally compatible now

### PR DESCRIPTION
**Pull request by mitchej123**

### CODE REVIEW

**Comment by Dream-Master** [comment]
@mitchej123 what this commit does ?

**Comment by mitchej123** [comment]
Removes an annoying boot msg :)

**Comment by repo-alt** [comment]
Was always funny to read those TiCo lamentations in the log :)

**Comment by mitchej123** [comment]
Haha, most of them are funny.  This one was just annoying considering we have a fork... and it's pretty well integrated with gregtech :-D

**Pull request merged**
